server:
  port: ${PORT}

aws:
  sqs:
    execution-event-changed-queue: https://sqs.us-east-1.amazonaws.com/446633124077/execution-event-changed
    execution-pnl-open-changed-queue: https://sqs.us-east-1.amazonaws.com/446633124077/execution-pnl-open-event-changed

redis:
  host: localhost
  port: 6379


feign-client:
  investment-management:
    url: https://investment-managment.herokuapp.com/api/
    name: investment-management
  hg-console:
    url: https://api.hgbrasil.com/finance/
    name: hg-console
