server:
  servlet:
    contextPath: /api

aws:
  accessKey: ${AWS_ACCESS_KEY:}
  secretKey: ${AWS_SECRET_KEY:}
  region: ${AWS_REGION:us-east-1}

cloud:
  aws:
    sqs:
      handler:
        default-deletion-policy: ON_SUCCESS


feign:
  client:
    config:
      hg-console:
        defaultQueryParameters:
          key: ${HG_CONSOLE_KEY}

user-id: user-id # This simulates a user logged in